# Generated by Django 2.0 on 2018-08-30 07:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0002_readnumdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readnumdetail',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
